# Generated by Django 2.0.2 on 2018-02-25 06:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20180224_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(unique=True)),
                ('category', models.PositiveIntegerField(choices=[(1, 'Content'), (2, 'Contract'), (3, 'User')])),
                ('contract', django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
    ]
